### ISSUE TITLE
Ler retorno sicred

### ISSUE THREAD

**Issue by Coopermine** [impactro/Boleto-Test#12]
Está implementado o retorno do SICRED?

Estou usando seu exemplo alterei a linha

 r.Init(new CedenteInfo { Banco = "748" });

Mas quando vou ler aparece

O método ou a operação não está implementada.
   em Impactro.Layout.CNAB400Sicredi.Retorno(String cData)
   em Impactro.Layout.LayoutBancos.Retorno(String cData)
   em BoletoForm2.frmRetorno.btnRetorno_Click(Object sender, EventArgs e) na C:\Users\korelio\Desktop\desss\Boleto-Windows-Form-master\frmRetorno.cs:linha 61

**Comment by impactro** [comment]
Não está implementado, deste banco só fiz a parte de remessa.
Me envie um arquivo de retorno anexo por e-mail (mpc.fabio@gmail.com) que eu implemento.

**Comment by Coopermine** [comment]
Enviado. Aproveitando a issue. Estou com problemas para gerar o boleto.
Na verdade ele gera mas não consigo fazer o pagamento.

```
Dim Cedente As Impactro.Cobranca.CedenteInfo = New Impactro.Cobranca.CedenteInfo

Cedente.Cedente = "Carambei Online Telecon Ltda - ME"
Cedente.CNPJ = "10.890.888/0001-39"
Cedente.Banco = "748"
Cedente.Agencia = "00730"
Cedente.Conta = "00730"
Cedente.Carteira = "3" 'SIMPLES SEM REGISTRO
Cedente.Convenio = "00730"
Cedente.CodCedente ="00730"
Cedente.Modalidade = "1" ' PARTICULAMENTE NÃO ENTENDI ESSA PARTE (BANCO SICREDI)



Dim Sacado As Impactro.Cobranca.SacadoInfo = New Impactro.Cobranca.SacadoInfo

Sacado.Sacado = "DAVID COOPER"
Sacado.Documento = "09580860793"
Sacado.Endereco = "RUA DOS ANJOS, 45"
Sacado.Cidade = "ITAPERUNA"
Sacado.Bairro = "CENTRO"
Sacado.Cep = "28460000"
Sacado.UF = "RJ"


Dim Boleto As Impactro.Cobranca.BoletoInfo = New Impactro.Cobranca.BoletoInfo
Boleto.Especie = Especies.DM
Boleto.NossoNumero = "145"
Boleto.NumeroDocumento = "1815"

Boleto.ValorDocumento = "100"
Boleto.DataDocumento = "12/04/2016"
Boleto.DataVencimento = "30/04/2016"
Boleto.PercentualMulta = "1"
Boleto.PercentualMora = "1"

Boleto.CalculaMultaMora = True


Dim blt As Impactro.Cobranca.Boleto = New Impactro.Cobranca.Boleto
blt.MakeBoleto(Cedente, Sacado, Boleto)
blt.CalculaBoleto()
```

Existe uma informação extra do banco quem me deram chamada "posto" e o valor é 08. Coloco esse valor junto com a agencia? talvez esse possa ser o erro.
(ps: codigo em vb.net) 

me add no skype: david.coopermine
Gostaria de comprar os fontes. Gostei bastante. Simples e funcional.

**Comment by impactro** [comment]
ola, dê uma olhada neste exemplo mais atual:

https://github.com/impactro/Boleto-ASP.NET/blob/master/BoletoNet/ExemploSicredi.aspx.cs#L22

O posto fica no campo modalidade e a carteira agora deve ser só com registro: 1

Cedente.Modalidade = "04"; // posto
Cedente.Carteira = "1"; // 1-Com Registro, 3-Sem registro
