### ISSUE TITLE
Nosso número com cálculo incorreto + recibo do pagador - Banco do Brasil

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-Test#13]
Verifique na diagramação do boleto: http://prntscr.com/axxb7h

Recibo do pagador: Informar endereço completo do beneficiário (rua, bairro, cep, uf, cidade)
Exemplo: http://prntscr.com/axxj3r

NOSSO NÚMERO: Informar sem DV. Caso deseje mantê-lo, verificar forma de cálculo, pois está incorreto.

Att.
ARTHUR BORGES
Unidade de Apoio

---

BANCO DO BRASIL S/A
CENOP Serviços - Recife
0800 729 0500 - Demais localidades
3003 0500 - Capitais
cenop.recife.suportetecnico@bb.com.br

**Comment by impactro** [comment]
Com relação a exibir o endereço no recibo, tudo dá para fazer, mas apenas para me resguardar, teria como me passar o link do documento do Banco do Brasil que exige isso, mas acho que a melhor forma seria resolver por exemplo de customização se for só o BB que estiver exigindo isso.

Já com relação ao digito verificador, preciso de todos os parâmetros usados, e principalmente saber qual seria o numero esperado, para poder confrontar a formula.

**Comment by diogolovizon** [comment]
[Doc5175Bloqueto.pdf](https://github.com/impactro/Boleto-Test/files/245657/Doc5175Bloqueto.pdf)

Segue manual em anexo, ver página 3 (item 2.2.2) e pág. 22. referente ao recibo do sacado e cálculo do nosso número. Abraço!

**Comment by impactro** [comment]
Fiz a adaptação no componente, apenas para o layout Web HTML, para exibir o endereço do sacado, basta habilitar uma nova propriedade, pois preciso tentar manter compatível, mas a exibição destas informações prejudica o layout.

https://github.com/impactro/Boleto-ASP.NET/blob/master/BoletoNet/ExemploBancoDoBrasil.aspx.cs#L57

Quanto ao digito do nosso numero, de acordo com o exemplo da página 17 da documentação está correto, fiz um teste unitário para comprovar isso, então preciso de um exemplo ou uma justificativa que aponte exatamente o erro.

https://github.com/impactro/Boleto-Test/blob/master/BB.cs#L29
