### ISSUE TITLE
Erro remessa banco do Brasil

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#14]
[cb280401.txt](https://github.com/impactro/Boleto-Test/files/243259/cb280401.txt)

Esse é o remessa gerado.

O banco está retornando o seguinte:

Considerando o seguinte convênio:
------------------------ Detalhamento do Convenio ----------------------------
  Agencia       :       2426 0 - PEDREGULHO  
  Beneficiario  :       9406 4 - PALOMA ABRAO SILVA - ME  
  Cart/Variacao :     17/019 SIMPLES COM REGISTRO  
  Tipo Convenio :          4 Cliente: Numera, emite e expede  
  Situacao      :          1 Normal com retorno  
  Nr.Convenio   :    2880310               Nr.Conv.Lider   : 2880310            
##   Tipo Ret.Lider:          6 CNAB240 - Ger.Financ./Mainf-Mainf 

Segue Arquivo "cb280401.rem" analisado:
**************\* Análise do Arquivo Remessa *************
# Foram detectadas as seguintes inconsistências:
## Header de Arquivo > Lote 0000
# Posições 033 a 052: Preencher com o código do convênio: '002880310001417019 '
## Header de Lote > Lote 0001
# Posições 034 a 053: Preencher com o código do convênio: '002880310001417019 '
## Segmento P > Lote 0001
# Posições 106 a 106: Preencher com branco

Após promover as alterações, favor gerar um novo arquivo e enviar-nos para continuidade do atendimento.

Atenciosamente,

Unidade de Apoio

---

BANCO DO BRASIL S/A
CENOP Serviços - Recife
0800 729 0500 - Demais localidades
3003 0500 - Capitais
cenop.recife.suportetecnico@bb.com.br

Na geração da remessa estou passando como abaixo:

```
    'Informações do ceente
    Dim ced As Impactro.Cobranca.CedenteInfo
    ced = New CedenteInfo()

    ced.Banco = "001" 'Banco Brasil
    ced.Cedente = CedenteNome 'Recebe o nome do Cedente
    ced.CNPJ = CedenteCNPJ 'Recebe o CNPJ do Cedente
    ced.Agencia = BcoAgencia 'Número da agencia
    ced.Conta = BcoCC 'Número da Conta Corrente
    ced.Carteira = BcoNCarteira 'Número da Carteira
    ced.CedenteCOD = BcoNCedente 'Número do Cedente
    ced.Convenio = BcoConvenio

    'Informações do Layous tem que ficar fora do laço (While)
    'LayoutBancos
    Dim sac As Impactro.Cobranca.SacadoInfo
    sac = New SacadoInfo

    Dim ret As Impactro.Layout.LayoutBancos
    ret = New Impactro.Layout.LayoutBancos
```

no banco convênio,está chegando a informação do convênio 2880310

Uma observação. se eu passar 002880310001417019 o campo informa que o convênio é invalido.

Estou utilizando a ultima versão disponibilizada no google driver.

No aguardo.

Atencipados agradecimentos.

**Comment by impactro** [comment]
Ola, bom dia.
O banco está querendo o layout CNAB240, e nativamente, e tenho só o CNAB400 por enquanto.
Com os fontes, acho que você deve ter tentado adaptar o layout de outro banco, mas os campos não são todos exatos, e tem que sempre fazer alguns ajustes, mas pelo visto você quase conseguiu.

Recentemente criei um artigo aqui na wiki, explicando como é esse processo, dá uma olhada

https://github.com/impactro/Boleto-Test/wiki/Criando-Layouts

No site do Banco do Brasil, achei o layout, que é de set/2009, o que em geral não costuma mudar:

http://www.bb.com.br/docs/pub/emp/empl/dwn/001IntroEstru.pdf

Vou começar a implantar, e assim que eu tiver pronto, atualizo este post, e você baixa a nova versão para testar, e homologar.

**Comment by jbsr** [comment]
Bom dia Fábio

Não, não fiz nenhum alteração na dll.

Vou aguardar a sua atualização.

Att

Jeferson

**Comment by jbsr** [comment]
Fábio, qual a função que utilizo para informar o formato de saída da REMESSA?

**Comment by jbsr** [comment]
Fábio, o cliente alterou o padrão do banco e está no CNAB 400.

Lembrando que não foi feito nenhuma alteração na dll. Estou utilizando a sua DLL padrão.
[cb090501.txt](https://github.com/impactro/Boleto-Test/files/255713/cb090501.txt)

(O caso da carteira alterei.)
O banco reportou a seguinte mensagem:

Prezado cliente,
    Analisamos o Arquivo Remessa "cb090501", conforme convênio abaixo:

Agencia       :       2426 0 - PEDREGULHO  
Beneficiario  :       9406 4 - PALOMA ABRAO SILVA - ME  
Cart/Variacao :     17/019 SIMPLES COM REGISTRO  
Tipo Convenio :          4 Cliente: Numera, emite e expede  
Situacao      :          1 Normal com retorno  
Nr.Convenio   :    2880310                                                    

## Tipo Retorno  :          5 CBR641/643 - Gerenciador Financeiro                                                  

Análise Arquivo Remessa

Arquivo Remessa enviado no formato CNAB 400 (CBR 641/643), conforme padrão cadastrado para o convênio 2880310, apresenta inconsistências conforme análise abaixo.

# 

##  Header do Arquivo 

Posições 032 a 039: Preencher com o número da conta corrente do convênio: '00009406'

#                                                                Informado:[00000000]

##  Detalhe tipo 7

Posições 023 a 030: Preencher com o número da conta corrente do convênio: '00009406'                                                                Informado:[00000000]
Posições 092 a 094: Preencher com a variação da carteira de cobrança. Ou seja: 019
                                                                    Informado:[017]

## Posições 159 a 160: Preencher com um código válido para a instrução codificada 02 (vide leiaute), de acordo com o comando '01'

Arquivo Remessa Não Validado/Homologado

```
Solicitamos efetuar os ajustes acima indicados e reenviar-nos o arquivo para nova análise. 
```

OBS.: Estamos enviando em anexo o manual “CBR 641 - Leiaute CNAB 400” para convênio de 7 posições, para auxiliar na parametrização do arquivo remessa.

Aguardos instruções

[cb090501.txt](https://github.com/impactro/Boleto-Test/files/255714/cb090501.txt)
[CBR 641 - Leiaute CNAB 400.pdf](https://github.com/impactro/Boleto-Test/files/255715/CBR.641.-.Leiaute.CNAB.400.pdf)

**Comment by impactro** [comment]
Ola, é preciso montar o "Cedente.CedenteCOD" com o layout abaixo, que pode variar em alguns casos de acordo com o tipo de carteira, mas no seu caso conforme a documentação fornecida é composta por:

9(004) Número da Agência onde está cadastrado o
X(001) D.V.  do Prefixo da Agência
9(008) Número da conta onde está
X(001) D.V.  do Número da Conta Corrente do Cedente
9(006) Complemento do Registro: “000000”

Já o outro campo, trata-se da instrução, se você informar juros, precisa colocar no campo boleto.intrucao1 o código 1

**Comment by jbsr** [comment]
Fábiio, o CedenteCod está sendo passado da seguinte forma:

Agencia: 34912
C/C: 00009406
Carteira: 19
Convenio: 2880310
Modalidade: 21

Com base nesses dados o Número do Cedente (Código do Cedente) está sendo passado da seguinte forma:

349120000940600000

Seria isso?

**Comment by impactro** [comment]
9(004) Número da Agência onde está cadastrado: **3491**
X(001) D.V. do Prefixo da Agência: **2**
9(008) Número da conta onde está: **00000940**
X(001) D.V. do Número da Conta Corrente do Cedente: **6**
9(006) Complemento do Registro: “**000000**”

O numero correto é: 3491-2-00000940-6-000000 => 34912000009406000000

Faltou dois dígitos, um na conta e outro no final
