### ISSUE TITLE
CAMPOS 111 A 117 SAO O SEQUENCIAL DA REMESSA, ELES ESTAVAM MANDANDO COMO 24, QUANDO O CORRETO E 0000024, 0000025 ASSIM POR DIANTE

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-Test#16]
SEGUE RETORNO DO SETOR RESPONSAVEL:

Exemplo: http://prntscr.com/b3nko1

ORIENTACAO E PARA QUE O SEU PROGRAMADOR REVISITE O MANUAL ... DOIS ERROS BASICOS QUE FORAM CORRIGIDOS.

OS CAMPOS 111 A 117 SAO O SEQUENCIAL DA REMESSA, ELES ESTAVAM MANDANDO COMO 24, QUANDO O CORRETO E 0000001, 0000002 ASSIM POR DIANTE

DENTRO DO ARQUIVO ESTAO COLOCANDO UMA DATA NO CABECALHO, ESSA DEVE SER A DATA DO NOME DO ARQUIVO ... DENTRO ESTAVA 04/05 ENQUANTO FORA ESTA 06/05

SE NAO CORRIGIREM ISSO, CONTINUARA TENDO PROBLEMAS PARA MANDAR A REMESSA.

CID:IMAGE003.JPG@01D1AB62.E54ABC00

**Comment by impactro** [comment]
Ola, bom dia

Com relação ao valor numerico, já corrigi, no arquivo: "Layout\CNAB400\CNAB400Sicredi.cs"
Era só mudar o tipo de dado de **PX** para **P9** ([RegFormat(RegType.P9, 7)])

Eventualmente em casos de problemas de conversão em geral a solução é sempre essa, já que quando crio um layout eu sempre copio de outro banco, e altero o que é diferente, ai qualquer ajuste você mesmo com os fontes, pode fazer, e depois dando tudo certo, você pode apenas enviar o que mudou para eu por nos fontes oficial, mantendo assim a compatibilidade.

Outra solução paliativa nestes casos é informar o valor como string incluindo os zeros "0000123", e depois eu mudo.

Digo isso para que você consiga agilizar seu lado sem ficar muito na minha dependência.

**Comment by impactro** [comment]
O segundo problema das datas não entendi, mas deve ser o nome do arquivo, ou algo do tipo.

**Comment by diogolovizon** [comment]
Entendi, neste caso ficaria assim: http://prntscr.com/b3xt4m ? Eu não fazia
ideia que mudando isso alterava esse valor. Vou tentar compilar aqui.
Obrigado!

Em sáb, 14 de mai de 2016 às 10:27, Fabio Ferreira de Souza <
notifications@github.com> escreveu:
