### ISSUE TITLE
Remessa sicredi  CAMPOS 111 A 117 mostrar 0000001, 0000002

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-Test#17]
Efetuei a alteração necessária, entretanto, não sofreu efeito.
Veja exemplo--> http://prntscr.com/b4s8rn e http://prntscr.com/b4scsa

------------------------------------------------------ // ------------------------------

Também tentei forçar a sequencia, exemplo:  var seq = $"{lote + totalRemessa:D7}";

 boleto.SetRegEnumValue(RegType.P9, 7);
 var seq = $"{lote + totalRemessa:D7}";
boleto.SetRegEnumValue(CNAB400HeaderSicredi.NumeroRemessa, seq); OU
boleto.SetRegEnumValue(CNAB400HeaderSicredi.Sequencia, seq);

**Comment by impactro** [comment]
Tem razão, definindo diretamente não vai, pois o sistema internamente converte para números, a menos que você iniciasse a numeração com um valor alto por exemplo:

boleto.SetRegEnumValue(CNAB400HeaderSicredi.NumeroRemessa,"1000123");

Mas independente já corrigi, e atualizei a pasta com os fontes e a versão compilada, é só baixar lá do Google Drive.

**Comment by diogolovizon** [comment]
Show Fábio, deu certo!

Em qui, 19 de mai de 2016 às 07:43, Fabio Ferreira de Souza <
notifications@github.com> escreveu:
