### ISSUE TITLE
Erro arquivo de Remessa

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#19]
Boa tarde Fábio

Preciso de informações pra passar informações da variação da carteira. Não encontrei essa opção na dll.

Há outros erros apresentados e as informações estão sendo passadas corretamente.

Segue informação passada pelo banco:

Conforme análise, verificamos:
## Detalhe tipo 7

Posições 004 a 017: Preencher com o número de inscrição correto para o convênio: 09226878000114
Posições 092 a 094: Preencher com a variação da carteira de cobrança. Ou seja: 019
Posições 221 a 234: Preencher com número de inscrição do sacado
Posições 235 a 271: Preencher com o nome do sacado

Se puder disponibilizar um exemplo em VB6 fico agradecido.
[1506201641.txt](https://github.com/impactro/Boleto-Test/files/319109/1506201641.txt)

Att

**Comment by impactro** [comment]
Ola, 

Esse tipo de registro eu não tenho nativamente no meu componente, pelo que pude perceber na minha versão dos fontes, e no arquivo anexo, pelo inicio das linhas.

Essa estrutura foi feita por outra pessoa, e por eu não ter o código não tenho como nem analisar.

01REMESSA01COBRANCA...
70100922687800114242600000940642880310...
70100922687800114242600000940642880310...
70100922687800114242600000940642880310...
9...

**Comment by jbsr** [comment]
Bom dia Fábia. Não esse arquivo foi gerado através da sua dll. Eu não tenho outra dll que não seja a suma.

O comando que está gerando o arquivo e remessa é o comando abaixo:

Dim ced As New CedenteInfo
Set ced = New CedenteInfo

ced.cedente = DLookup("[CedenteNome]", "boletos_confg", "[ID]=" & Me.Carteira.Column(0))
ced.CNPJ = DLookup("[CedenteCNPJ]", "boletos_confg", "[ID]=" & Me.Carteira.Column(0))

```
ced.Banco = DLookup("[BcoNun]", "boletos_confg", "[ID]=" & Me.Carteira.Column(0))
ced.Agencia = DLookup("[CDAgencia]", "boletos_confg", "[ID]=" & Me.Carteira.Column(0))
ced.Conta = Format$(DLookup("[CtaCorente]", "boletos_confg", "[ID]=" &    Me.Carteira.Column(0)), "0000000000")
ced.Carteira = DLookup("[NCarteira]", "boletos_confg", "[ID]=" & Me.Carteira.Column(0))
```

Dim ssql As String
Dim rst As Recordset

ssql = ""
ssql = "Select \* From Processamentos_Parcelas where ID=" & Me.Carteira.Column(0) & " and DataProcessamento=#" & Format$(Me.DTP, "mm/dd/yyyy") & "#"
Set rst = CurrentDb.OpenRecordset(ssql)    'abre o recordeset

Dim sac As New SacadoInfo

Dim nct
nct = 1

'Informações do Layous tem que ficar fora do laço (While)
Dim ret As New LayoutBancos
ret.Init ced
ret.ShowDumpLine = False    'Exibe informações de posição / valor
ret.Lote = 1

While (Not rst.EOF)

```
sac.Sacado = rst("SacadoNome").Value
sac.Endereco = rst("SacadoEnd").Value & "," & rst("SacadoNun").Value
sac.Bairro = rst("SacadoBairro").Value
sac.Cidade = rst("SacadoMunicipio").Value
sac.UF = rst("SacadoUF").Value
sac.Cep = rst("SacadoCEP").Value

Dim bol As New BoletoInfo
bol.NossoNumero = rst("NossoNumero").Value
bol.ValorDocumento = rst("VrBoleto").Value
bol.DataDocumento = rst("DataProcessamento").Value
bol.DataVencimento = rst("DataVencimento").Value
bol.Especie = Especies_DM

bol.Ocorrencia = Ocorrencias_Remessa
bol.Comando = 1


ret.Add bol, sac
rst.MoveNext
```

Wend

'Gera o arquivo de remessa
ret.RemessaTo (fileRemessa)

Então não tem como ser gerado através de outro recurso que não seja o seu.

Nessa instrução não sei o que falta para colocar a variação da carteira.

Basta me passar um exemplo preciso de como gerar a remessa para o BB, pois há falta de informação.

No aguardo.

Att
