### ISSUE TITLE
Remessa do Bradesco Erro ao trocar  a Condição para Emissão da Papeleta de Cobrança posição 93

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-Test#2]
Remessa Bradesco CNAB400.

Linha exemplo:
`100000000000000000000009012300040510800000000000000000009614130002000200000001204400000000002S           0  01000000120431011600000000888730000000001N301215061000000000000302001160000000008000000000000000000000000000000100000268216487TESTE, QUADRA 14 - LOTE 13            RUA DA AMIZADE, 203/402                             52011260                                                            000002`

A condição abaixo não está alterando o item "Condição para Emissão da
Papeleta de Cobrança" posição 93

`boleto.SetRegEnumValue(CNAB400Remessa1Bradesco.Condicao, 1);`

Exemplo remessa: http://prntscr.com/aaa8y1
Exemplo documento: http://prntscr.com/aaabaj

Conforme o exemplo acima deveria mudar para "1"S, entretanto, continua o código "2"S

Versão da DLL: 2.16.2.24

**Comment by impactro** [comment]
Realmente, já vi o código e realmente está com o mesmo problema o Bradesco e o Santander.
Vou corrigir, testar e logo mais disponibilizo uma atualização.

**Comment by diogolovizon** [comment]
Show!

Em qui, 3 de mar de 2016 08:14, Fabio Ferreira de Souza <
notifications@github.com> escreveu:

**Comment by diogolovizon** [comment]
Se precisar de mais informações que ajude na correção, por favor, encaminhe um e-mail.
Abs!

**Comment by impactro** [comment]
OK Diogo, publiquei as alterações.
Baixe e compile os fontes do GoogleDrive, ou apenas o UPDATE dentro da pasta de exemplos.
