### ISSUE TITLE
Remessa do banco Itaú - Nº DO BANCO NA CAMARA DE COMPENSACAO

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-Test#21]
[valida_E0800001REM.pdf](https://github.com/impactro/Boleto-Test/files/320975/valida_E0800001REM.pdf)
[Layout ITAU.pdf](https://github.com/impactro/Boleto-Test/files/320974/Layout.ITAU.pdf)

DANILO Cliente 17/06/2016 09:51
BOM DIA.

O BANCO RETORNOU INFORMANDO QUE O LAYOUT ESTA ERRADO.

SEGUE ABAIXO O ERRO:

LAYOUT: ITAU - COB. COM REGISTRO - CNAB 400
REGISTRO: DETALHE
LINHA: 2
POSICAO 077 - CAMPO: N DO BANCO NA CAMARA DE COMPENSACAO - CONTEUDO FIXO DIFERE DO ESPERADO. (000)

Método usado para corrigir o problema:

`if (codigoBanco == "341")
                                {
                                    boleto.SetRegEnumValue(CNAB400Remessa1Itau.Banco, 341);
                                }`

O código acima não surgiu efeito, exemplo: http://prntscr.com/bhlsmr. 
O que preciso fazer? 

O cliente enviou a documentação que está em anexo.

**Comment by impactro** [comment]
Ola, 
Essa validação parece estar equivocada, pois na posição 77 no "Header" está sendo gerado o código do banco, conforme mostrado até no print, valor gerado através da definição da linha abaixo nos fontes **Layout\CNAB400\CNAB400Itau.cs**

/// <summary>


/// Nº DO BANCO NA CÂMARA DE COMPENSAÇÃO 
/// </summary>


[RegFormat(RegType.P9, 3, Default = "341")] // 77-79
CodigoBanco,

Mas, veja o layout de registro detalhe, não deve haver esse tipo de informação na posição 77 
![itau400registro](https://cloud.githubusercontent.com/assets/1304804/16180465/8e893598-365b-11e6-8521-b8c698f88888.PNG)

Sugiro contestar a validação com o banco.

**Comment by diogolovizon** [comment]
Olá Fábio, obrigado. Vou avisar o cliente sobre isso. Abraço!!

Em dom, 19 de jun de 2016 20:23, Fabio Ferreira de Souza <
notifications@github.com> escreveu:
