### ISSUE TITLE
urgente, banco do brasil!

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-Test#22]
As remessas estão indo com o valor em centavos, exemplo. Boleto de 5,00 vai como 0,05 na remessa.

Exemplo em anexo. É urgente!

**Comment by impactro** [comment]
Ola, realmente tem um erro de definição do tipo de dado.
Segue o que você precisa alterar na sua versão dos fontes:

No arquivo: Layout\CNAB400\CNAB400BB.CS apenas altera o Tipo do RegFormat de P9, para PV, veja abaixo a linha como deve ficar:

```
    /// <summary>
    /// Valor do Título #obs:19 
    /// </summary>
    [RegFormat(RegType.PV, 13)] // 127-139
    ValorDocumento,
```

Estou no meio de uma nova versão então não tenho como subir uma atualização agora.

**Comment by diogolovizon** [comment]
Obrigado Fábio, já fiz a alteração.. vou avisa-los!

Em sex, 8 de jul de 2016 às 08:04, Fabio Ferreira de Souza <
notifications@github.com> escreveu:

**Comment by diogolovizon** [comment]
Fábio, funcionou em partes, olha -> http://prntscr.com/bqfarb
Agora os centavos não são mostrados, ele só mostrar valores inteiros, exemplo: 130,16 ele vai como 130,00 no caso: correto 13016, vai como 13000.

Atributo usado:  boleto.SetRegEnumValue(RegType.PV, 13);

**Comment by impactro** [comment]
Dá uma procurado no mesmo arquivo, deve ser a mesma coisa mas em outros
campos.
Depois me passe o que você corrigiu, para eu deixar igual aqui

Em 8 de julho de 2016 12:56, diogolovizon notifications@github.com
escreveu:

> Fábio, funcionou em partes, olha -> http://prntscr.com/bqfarb
> Agora os centavos não são mostrados, ele só mostrar valores inteiros,
> exemplo: 130,16 ele vai como 130,00 no caso: correto 13016, vai como 13000.
> 
> Atributo usado: boleto.SetRegEnumValue(RegType.PV, 13);
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/impactro/Boleto-Test/issues/22#issuecomment-231398171,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABPo5KJIcpaUH2wBaImYgOW7at6ZGMWTks5qTnM2gaJpZM4JGBau
> .

## 

_Fábio Ferreira de Souza_
_Engenheiro Programador_
VB6 / C#.Net / ASP/ Java / Android / C++
Celular: (11) 9 6607-2730 Claro / WhasApp

**Comment by diogolovizon** [comment]
Fábio, atualize no seu projeto -> http://prntscr.com/bqt597
Fiz esta alteração e gerei a .dll novamente e funcionou. Só me confirme se a ultima versão é do dia 11/06/2016 no qual estamos trabalhando.
