### ISSUE TITLE
Erro da imagem do código de barras

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#23]
Fábio

Apos a geração do arquivo de imagem, ao ser passado pelo código de barras, ocorre que o leitor, em qualquer boleto, retorna apenas o valor de R$ 10,00.

Para a geração da imagem estou utilizando a função abaixo, que foi passada anteriormente por você:

```
    Dim cCodBar As String
    cCodBar = CodigoBarras
    Dim img As Bitmap = CobUtil.BarCodeImage(cCodBar)
    img.Save(rota_arquivo & NossoNumero & ".jpg", Imaging.ImageFormat.Jpeg)
```

Quando eu processo o boleto as informações retornadas são:

Código de Barras: 00191686100000050000000002880310000000117717
Linha Digitavel: 00190.00009 02880.310004 00001.177179 1 68610000005000
Nosso Número: 28803100000001177-0

Em CodigoBarras estou passando o valor retornado pela dll através da função 'Boleto.CodigoBarras'.

O valor passado é  00191686100000050000000002880310000000117717

Observe que estou passando um valor de R$ 50,00 e o código de barras me retorna uma valor diferente disso.

Os dados que estão sendo passados para a composição da Linha Digitavel e Código do Boleto são:
# 

Debug.Print cedente.cedente
Debug.Print cedente.CNPJ
Debug.Print cedente.Banco
Debug.Print cedente.Agencia
Debug.Print cedente.Conta
Debug.Print cedente.Carteira
Debug.Print cedente.Convenio
Debug.Print cedente.Modalidade
Debug.Print Boleto.Aceite
Debug.Print BoletoInfo.Especie
Debug.Print BoletoInfo.NossoNumero
Debug.Print BoletoInfo.NumeroDocumento
Debug.Print BoletoInfo.DataDocumento
Debug.Print BoletoInfo.DataVencimento
Debug.Print BoletoInfo.Quantidade
Debug.Print BoletoInfo.ValorUnitario
Debug.Print BoletoInfo.ValorDocumento
Debug.Print BoletoInfo.ParcelaNumero
Debug.Print BoletoInfo.ParcelaTotal
Debug.Print BoletoInfo.ValorDesconto
Debug.Print BoletoInfo.ValorOutras

Debug.Print nCD
Debug.Print nLinha
Debug.Print NNF

---

PALOMA ABRAO SILVA - ME
09226878000114
001
2426-0
9406-4
17
2880310
21
N
 1 
1177
00001
11/07/2016 
20/07/2016 
 1 
 50 
 50 
 1 
 1 
 0 
 0 
00191686100000050000000002880310000000117717
00190.00009 02880.310004 00001.177179 1 68610000005000
#28803100000001177-0

Em anexo o PDF e o arquivo de imagem.

Aguardo instruções.
[Boleto 50.pdf](https://github.com/impactro/Boleto-Test/files/366060/Boleto.50.pdf)
[Valores Debug.txt](https://github.com/impactro/Boleto-Test/files/366061/Valores.Debug.txt)

**Comment by impactro** [comment]
Ola, realmente levei um susto ao iniciar a validação deste problema.

Fiz vários testes com diversos aplicativos de leitores de código de barras, para Android e Windows Phone, e realmente está tudo certo, mas em geral os leitores não funcionam bem tentando ler código direto da tela, só funcionam mesmo lendo de papel, e mesmo assim precisam ter uma boa camera com foco

Como principal teste usei uma conta de um cartão de credito que recebi, e gerei o código de barras, e visualmente o conteúdo gerado é o mesmo, veja abaixo:  
![wp_20160716_15_04_11_pro_li](https://cloud.githubusercontent.com/assets/1304804/16896444/0b3ff3e2-4b6a-11e6-9745-31517ba92851.jpg)

O primeiro é o que eu gerei, note que está mais borrado pois foi impresso com uma impressora jato de tinta, que logico tem uma resolução menor que uma impressora laser, mas o tamanho, e o padrão é praticamente o mesmo.

O ruim é que a impressão de código de barras é feito com linhas da espessura de 1 pixel, ou 3 para os itens largos, e por causa disso a probabilidade de borrão é muito alto.

Ou seja, tudo certo, e infelizmente se a impressão não for boa, não é possível ler nada.
