### ISSUE TITLE
Erro Boleto Santander

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#24]
Fábio.

Encaminhei um boleto e o banco informou que a linha digitável do mesmo está errado.

Na dll verifique que há informação de modalidade, porem o banco informou que não há essa informação. Assim a mesma está sendo passada em branco. O que devo informar para o banco nesse campo?

ENVIADO         0339000069 76253000004 03200033086 8 68960000008100
ESPERADO    0339967622 53053000005 03200601015 1 68960000008100

Na imagem tem os dados de cliente e da carteira.

![2016-09-08_080611](https://cloud.githubusercontent.com/assets/17903664/18347529/7959bd2a-759c-11e6-83f0-d634b023b4fa.png)

No aguardo.

Att

**Comment by jbsr** [comment]
Fábio, estou passando os parâmetros como abaixo:

```
   ced.Cedente = "Cliente  SANTANDER"
    ced.Banco = "033"
    ced.Agencia = "3212–3"
    ced.Conta = "013002421–9"
    ced.Carteira = "101"
    ced.CNPJ = "12.345.678/0001-12"
    ced.CodCedente = "00006762530"
    ced.Convenio = "6762530"
    ced.Modalidade = "101"

    sac.Sacado = "ROMA"

    bol.NossoNumero = "1236"
    bol.DataDocumento = Now
    bol.DataVencimento = CDate("30/09/2016")

    bol.NumeroDocumento = "00001"
    bol.Quantidade = 1
    bol.ValorUnitario = "10,11"
    bol.ValorDocumento = "10,11"
    bol.ValorCobrado = "10,11"
    ' Mostra no recibo do pagador
    bol.Demonstrativo = "Exemplo de texto sobre o demostrativo"
    bol.LocalPagamento = "Pagavel em qualquer lugar possivel"
    bol.Instrucoes = "Instruções para o caixa"
    'Tipo de boleto
    bol.Aceite = "N"
    bol.Especie = "1"

    bol.Ocorrencia = 1
    bol.Comando = 1
    bol.Instrucao1 = 2
    bol.Instrucao1 = 3

    bol.DataDesconto = CDate("30/09/2016") 'Data Limite para a
    bol.ValorDesconto = 0
    bol.ValorOutras = 0
    bol.ValorAcrescimo = 0
    bol.ValorMora = 0  'Valor de mora por dia: R$ 0,10 (dez centavos)
    bol.PercentualMulta = 0 '2 / 100 '2% de multa
    bol.CalculaMultaMora = 0
    'Só em carne ou layout customizado
    bol.ParcelaNumero = 1
    bol.ParcelaTotal = 1

    'Executa os calculos de geraçào de boleto
    blt.MakeBoleto(ced, sac, bol)
    'blt.Save("teste.bmp")
    blt.CalculaBoleto()
```

Ao encaminhar o boleto para o banco para validação, eles me retornam o erro abaixo:

Cedente: 6762530
Cód. Da carteira: 101 – simples rápida com registro.
SOLUÇÃO

LINHA DIGITÁVEL
ENVIADO     0339676256 30000000015 23900033053 3 69330000001011
ESPERADO    0339967622 53000000017 23900701014 1 69330000001011

Aguardo instruções.

Att

**Comment by impactro** [comment]
No final de semana vou verificar o que pode ser.

Se quiser tentar achar, use o link para decodificar, e analisar o código de barras, que é mais fácil.
ai analisando os fontes você acha fácil o problema, o parâmetro que falta, ou que está errado.

http://exemplos.boletoasp.com.br/BoletoNet/FuncTeste_DecodIPTE.aspx

**Comment by jbsr** [comment]
Fábio, digite no site como orientou e ele me retornou conforme abaixo.

Não sei o que quer dizer e nem como analisar o código pois entendo muito pouco de C#

2016-09-09_103653.png

Se precisar conectamos e você me passa o custo das horas para solucionarmos o problema.

O cliente está me pressionando.

O que me chama a atenção é que para o BB eu já estou emitindo normal.

No aguardo.

Att

De: Fabio Ferreira de Souza [mailto:notifications@github.com] 
Enviada em: sexta-feira, 9 de setembro de 2016 10:07
Para: impactro/Boleto-Test
Cc: jbsr; Author
Assunto: Re: [impactro/Boleto-Test] Erro Boleto Santander (#24)

No final de semana vou verificar o que pode ser.

Se quiser tentar achar, use o link para decodificar, e analisar o código de barras, que é mais fácil.
ai analisando os fontes você acha fácil o problema, o parâmetro que falta, ou que está errado.

http://exemplos.boletoasp.com.br/BoletoNet/FuncTeste_DecodIPTE.aspx

**Comment by edertiago** [comment]
Bom dia pessoal, estou com um problema na emissão do boleto para o Santander também., o meu problema é um pouco diferente do caso do **jbsr**, se pudessem me ajudar agradeceria.
Quando tento gerar o boleto o método **MakeBoleto** me retorna um erro: _**Value was either too large or too small for an Int32.**_ 

Porem não consigo descobrir qual campo esta estourando, será que conseguem me ajudar.

Quanto ao erro do **jbsr** esta faltando um **9** não é? A documentação do Santander exige dois '9'... um para a Moeda 9 = Real, e um outro '9' FIXO.
Olha a minha linha digitavel.

03399539295190000001288346101012269390000156372

**Comment by impactro** [comment]
Conforme te disse anteriormente, dado as duas linhas digitáveis e o programa que decodifica, temos:
http://exemplos.boletoasp.com.br/BoletoNet/FuncTeste_DecodIPTE.aspx

ENVIADO (A) 0339676256 30000000015 23900033053 3 69330000001011 
CÓDIGO DE BARRAS (A) 033.9.3.6933.0000001011-6762530000000012390003305

ESPERADO (B) 0339967622 53000000017 23900701014 1 69330000001011
CÓDIGO DE BARRAS (B) 033.9.1.6933.0000001011-9676253000000012390070101

A linha digitável é de difícil entendimento pois alguns dígitos verificadores no meio.
Já o código de barras, o inicio é padrão, e apenas os 25 últimos digito varia de banco para banco, veja:

![image](https://github.com/impactro/Boleto-ASP.NET/blob/master/BoletoNet/Imagens/CodBarras_x_IPTE.png?raw=true)

Então comparando perceba

CÓDIGO DE BARRAS (A) 033.9.**3**.6933.0000001011-**6762530000000012390003305**
CÓDIGO DE BARRAS (B) 033.9.**1**.6933.0000001011-**9676253000000012390070101**

Na posição 5, os dígitos "3" e "1" são diferentes, pois são ditos verificadores, então se o restante estiver igual, estes serão iguais, automaticamente, então vamos ao que interessa, os 25 últimos dígitos:

CAMPO LIVRE (A) 6762530000000012390003305
CAMPO LIVRE (B) 9**6762530**00000012390070**101**

O campo livre B está de acordo com o padrão Santander

![image](https://cloud.githubusercontent.com/assets/1304804/18421699/b7474a36-7866-11e6-8fa1-76b476d4f556.png)

Já o campo livre A está de acordo com a antiga logica do Banespa

![image](https://cloud.githubusercontent.com/assets/1304804/18421832/24871e58-7869-11e6-8212-4d7d6579880a.png)

No meu componente, na configuração do **CedenteInfo**, existe a flag "**useSantander**" que remapeia a rotina do Banespa para usar o a Rotina do Santander

![image](https://cloud.githubusercontent.com/assets/1304804/18421849/7d3fbed8-7869-11e6-8b67-15954c2ab278.png)

experimente usar: sac.useSantander = true; // o padrão é false
