### ISSUE TITLE
Ler arquivo de retorno

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#26]
Fábio, qual o comando utilizando para receber os dados da 'data do credito' no arquivo de retorno?

Não encontrei essa função na aplicação.

Att

**Comment by impactro** [comment]
Usando como referencia o arquivo dos fontes da DLL em "Cobranca\Layout\CNAB400\CNAB400BB.cs" no enumerador de estrutura de layout "CNAB400Retorno1BB" o que existe é apenas a "OcorrenciaData" na posição 111

[RegFormat(RegType.PD, 6)] // 111
OcorrenciaData,

Cada banco tem campos distintos, eu tento padronizar via componente, mas a ideia de vender os fontes é dar a opção de cada um extrair o que quiser como nome que quiser, já que os bancos adotam padrões diferentes, e cada sistema trabalha diferente, o importante é entender a rotina de retorno de cada classe, por exemplo, a do Banco do Brasil eu só leio os seguintes nas variáveis mais comum:

public override Layout Retorno(string cData)
        {
            Layout retorno = new Layout(typeof(CNAB400Retorno1BB));
            retorno.onInvalidLine += Retorno_onInvalidLine;
            retorno.Conteudo = cData;
            retorno.ForEach<CNAB400Retorno1BB>(reg =>
                Boletos.Add(new BoletoInfo()
                {
                    DataDocumento = (DateTime)reg[CNAB400Retorno1BB.OcorrenciaData],
                    NossoNumero = (string)reg[CNAB400Retorno1BB.NossoNumero],
                    NumeroDocumento = (string)reg[CNAB400Retorno1BB.NumeroDocumento],
                    ValorDocumento = (double)reg[CNAB400Retorno1BB.ValorDocumento],
                    DataVencimento = (DateTime)reg[CNAB400Retorno1BB.Vencimento],
                    DataPagamento = (DateTime)reg[CNAB400Retorno1BB.DataPagamento],
                    ValorPago = (double)reg[CNAB400Retorno1BB.ValorPago]
                }, reg.OriginalLine)
            );
            return retorno;
        }
