### ISSUE TITLE
Dll não lê arquivo de retorno do Banco do Brasil

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#27]
Fábio, estou com dois padrões de arquivo aqui CB260 e CB400.

A função ret.BoletoCount   não está identificando nenhum dos registros.

[IEDCBR243212201625151.txt](https://github.com/impactro/Boleto-Test/files/633877/IEDCBR243212201625151.txt)
[IEDCBR2476212201625044.txt](https://github.com/impactro/Boleto-Test/files/633878/IEDCBR2476212201625044.txt)

Aguardos instruções.

Att

**Comment by impactro** [comment]
Ola, bom dia.

O Layout implementado para o Banco do Brasil é apenas o CNAB400, tanto para remessa como para retorno, conforme indicado na lista de bancos e layouts suportados: 
https://github.com/impactro/Boleto-Test/wiki/Bancos-Suportados

Em geral os bancos disponibilizam ambas as versões para o usuário baixar o retorno, procure o arquivo CNAB400, que é o layout mais recente e que tem sido adotado pela maioria dos bancos.
