### ISSUE TITLE
Dll não lê arquivo de retorno do Banco do Brasil  (referencia ao chamado #27)

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#28]
Fábio, o que ocorre é que o banco informa quer o arquivo fornecido é CNAB 400.

Fiz a contagem de ambas as linhas e eles tem 400 caracteres como manda o manual, contudo, a dll não está lendo o mesmo.

Gentileza verificar, pois estou sem argumento com o banco. Preciso saber porque esse arquivo não é um CANAB400.

No aguardo.

Att
[CBR6433402511201614714.txt](https://github.com/impactro/Boleto-Test/files/639233/CBR6433402511201614714.txt)

**Comment by impactro** [comment]
Ola, bom dia.
O meu componente atualmente só lê registros de tipo 1, usado em outro tipo de convenio.
Mas consegui apenas começar o exemplo de como ler outros tipos de linha customizadas.
Devo terminar nos próximos dias de ler todos os campos, mas segue um exemplo de como fazer isso, caso não possa esperar.

https://github.com/impactro/Boleto-Test/blob/master/BB_Retorno7.cs
