### ISSUE TITLE
Arquivo Retorno Santander CNAB400

### ISSUE THREAD

**Issue by contatoaugusto** [impactro/Boleto-Test#29]
Alguém teria um arquivo de retorno do Santander CNAB 400 como exemplo? Algo simples mesmo, poucas linhas pra que eu possa fazer testes e continuar co a aplicação. Já procurei por todos os lugares, inclusive, já pedi diversas vezes pro próprio Santander, mas eles ainda não me enviaram.

Obrigado

**Comment by impactro** [comment]
Ola Augusto, só a rotina base do Santander CNAB400 tem 773 linhas.
Isso usando diversas rotinas e chamadas externas do componente.
O Banco fornece o layout, e fica aos programadores desenvolver de acordo com suas necessidades.
O componente que tenho gera apenas os registros obrigatórios, padrão, por isso, só vendo os fontes, pois as vezes ainda é necessário implementar coisas a mais em cima do que eu forneço
