### ISSUE TITLE
Informações de "SAC" no boleto da Caixa

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-Test#3]
Uma homologação foi reprovada por não existir as informações de "SAC" no boleto.
Tentei achar alguma configuração referente ms não encontrei... existe algo do gênero?

--------------------------------------------------- // -------------------------------------------

A4706RJ - AG Vila Kosmos/RJ

C/C RERET4706RJ - RERET VILA KOSMOS/RJ

Sr. Gerente,

> 1. Informamos que as informações do SAC não foram inseridas no recibo do pagador e as margens do código de barras não foram regularizadas.

**Exemplo na documentação:**
http://www.caixa.gov.br/downloads/cobranca-caixa-manuais/ESP_COD_BARRAS_SIGCB_COBRANCA_CAIXA.pdf

Incio na página 6 item 3.2.2 do link acima.

**Comment by impactro** [comment]
Você pode especificar diretamente nas informações do boleto como no [exemplo](https://github.com/impactro/Boleto-ASP.NET/blob/8bbe1a76cd6de52830eea2e85ee23948addaa2bd/Registro/CNAB-RemessaSimples.aspx.cs#L67)

`Cedente.Informacoes =
            "SAC CAIXA: 0800 726 0101 (informações, reclamações, sugestões e elogios)<br/>" +
            "Para pessoas com deficiência auditiva ou de fala: 0800 726 2492<br/>" +
            "Ouvidoria: 0800 725 7474 (reclamações não solucionadas e denúncias)<br/>" +
            "<a href='http://caixa.gov.br' target='_blank'>caixa.gov.br</a>";
`
