### ISSUE TITLE
Geração da remessa Santander

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-Test#4]
Fábio,
Por alguma razão que ainda não consegui detectar, estou recebendo uma exception na hora de gerar remessa do santander..

Segue mensagem:

> Exception.Message : Erro ao gerar linha por causa do campo: MultaPercentual (PV) 4 - Inner: Tamanho 5 ultrapassa o espaço necessario para o número: '20000' PV(4) 

Sabe me informar qual é o problema? ou o que está ultrapassando este tamanho, sabendo que o campo multapercentual é "2.0"

Abraço!

**Comment by impactro** [comment]
o valor da multa está estourando, deve ser um percentual, e não um valor
monetário. (valor de 0 a 99.99)

Em 15 de março de 2016 14:37, diogolovizon notifications@github.com
escreveu:

> Fábio,
> Por alguma razão que ainda não consegui detectar, estou recebendo uma
> exception na hora de gerar remessa do santander..
> 
> Segue mensagem:
> 
> Exception.Message : Erro ao gerar linha por causa do campo:
> MultaPercentual (PV) 4 - Inner: Tamanho 5 ultrapassa o espaço necessario
> para o número: '20000' PV(4)
> 
> Sabe me informar qual é o problema? ou o que está ultrapassando este
> tamanho, sabendo que o campo multapercentual é "2.0"
> 
> Abraço!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/impactro/Boleto-Test/issues/4

## 

_Fábio Ferreira de Souza_
_Engenheiro Programador_
VB6 / C#.Net / ASP/ Java / Android / C++
Celular: (11) 9 6607-2730 Claro / WhasApp

**Comment by diogolovizon** [comment]
Fábio, fiz uma revisão dos valores que estou passando pra ver se tinha algo fora do normal.
Entretanto, todos os valores estão "corretos" veja abaixo os prints dos dados:

**Dados do boleto:**
1° http://prntscr.com/afyyex
2° http://prntscr.com/afyymu
3° http://prntscr.com/afyxn9

**Dados do Sacado:**
1º http://prntscr.com/afyzg8

**Dados do Layout:**
1º http://prntscr.com/afz0kt
2º http://prntscr.com/afz13i <---- acho que tem algo importante aqui 
3º http://prntscr.com/afz2ax
4º http://prntscr.com/afz36n

Realmente não sei lhe dizer o que houve de mudança, mas todos os registros gerados pelo Santander estão com o mesmo problema.

Espero que as informações acima ajude a descobrir ou me orientar no que fazer, acredito que dados não seja o problema pois como nos prints dos boletos não existe nada "anormal"
Se precisar de mais informações estou disponível.

**Comment by impactro** [comment]
Esse caso está difícil de analisar.
Há 2 formas de tentarmos resolver isso:

1) Referencie no seu projeto os fontes da DLL e remova a dependência da DLL fechada, assim o erro irá ocorrer dentro da linha do meu código, e você poderá entender qual parâmetro está danificando a logica.

2) Ou agendamos um acesso remoto, e eu realizo exatamente o vinculo acima, já corrigindo o que tiver que ser corrigido, logo mais conversamos pelo whtas app para ver como faremos

**Comment by impactro** [comment]
Ola, Realmente era um BUG!
O valor estava como sendo do tipo "PV" (Valor) mas também multiplicado por 100 então estourava.
Já publiquei um UPDATE e atualizei os fontes lá no Google Drive

**Comment by diogolovizon** [comment]
Perfeito Fábio, parabéns.. funcionou!

Em qua, 23 de mar de 2016 às 08:20, Fabio Ferreira de Souza <
notifications@github.com> escreveu:
