### ISSUE TITLE
Gerar aquivo de Remessa - VB6

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#5]
Prezados

Observei no código (vb6) no exemplo é processado a remessa para um único casaco. 

Como poderia processar a remessa quando o sacado é diferente para cada boleto?

Att

**Comment by impactro** [comment]
Fiz dessa forma para simplificar o exemplo, mas você pode instanciar normalmente no mesmo loop um sacado para cada boleto da mesma forma que é feito os boletos.

Depois vou preparar um exemplo mais completo e subir aqui.

**Comment by jbsr** [comment]
Fábio, fiz isso, mas ele não monta o arquivo de remessa corretamente.

Poderia me encaminhar o exemplo?

**Comment by jbsr** [comment]
Veja como está gerando:

01REMESSA01COBRANCA       00000000000001111111SYSMATOS                      237BRADESCO       210316        MX0000123                                                                                                                                                                                                                                                                                     000001
100000000000000000000009035220045150900000000000000000000000000000000000000000070400000000002S           0  01000000000001031600000000015000000000001N210316000000000000000000000000000000000000000000000000000000000000000100000000000000CLIENTE TESTE2                          AV. PAULISTA,300                                    30662260                                                            000002
9                                                                                                                                                                                                                                                                                                                                                                                                         000003

Tudo em uma mesma linha.

passei os parametros da seguinte forma:

Dim ssql As String
    Dim rst As Recordset

```
ssql = ""
ssql = "Select * From Processamentos_Parcelas where ID=" & Me.Carteira.Column(0) & " and DataProcessamento=#" & Format$(Me.DTP, "mm/dd/yyyy") & "#"
Set rst = CurrentDb.OpenRecordset(ssql)    'abre o recordeset

Dim sac As New SacadoInfo
While (Not rst.EOF)

    sac.Sacado = rst("SacadoNome").Value
    sac.Endereco = rst("SacadoEnd").Value & "," & rst("SacadoNun").Value
    sac.Bairro = rst("SacadoBairro").Value
    sac.Cidade = rst("SacadoMunicipio").Value
    sac.UF = rst("SacadoUF").Value
    sac.Cep = rst("SacadoCEP").Value

    Dim ret As New LayoutBancos
    ret.Init ced

    Dim bol As New BoletoInfo
    ret.Lote = 123

    bol.NossoNumero = rst("NossoNumero").Value
    bol.ValorDocumento = rst("VrBoleto").Value
    bol.DataDocumento = rst("DataProcessamento").Value
    bol.DataVencimento = rst("DataVencimento").Value
    ret.Add bol, sac

    rst.MoveNext

Wend
```

Dentro do recordeset são passados 03 registros: Cliente 1, Cliente 2 e Cliente 3, cada um com seu boleto. Observe que foi gerado apanas para o 03

**Comment by jbsr** [comment]
Fábio, já identifique como gerar o arquivo corretamente.

Mas restou uma duvida. A instrução ret.Lote 

No seu exemplo esta 123 - ret.Lote = 123

è o código que identifica o lote do arquivo de remessa? Ele deve ser alterado de arquivo para arquivo? Existe alguma particularidade ou observação quanto ele? Ele tem a ver com a quantidade de arquivo de remessa gerado para um mesmo banco?

**Comment by impactro** [comment]
Isso perfeita dedução.
A ideia é que você tenha em seu sistema algum contador de lote, que a cada geração incremente esse numero, e você gere assim lotes diferentes para cada arquivo.

Respondendo a pergunta anterior, há 2 métodos que retornam a remessa:
- Remessa() - Que retorna uma string, para você gerar o arquivo, gravar em banco ou fazer o que quiser
- RemessaTo(arq) - Que já salva o arquivo no local informado
