### ISSUE TITLE
Erro Remessa Santander 033

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#7]
Prezado

Esse é o código utilizado:

```
' SANTANDER
```

ced.Banco = "033"
ced.Agencia = "1234-1"
ced.Conta = "1234567896"
ced.CodCedente = "1231230"
ced.Carteira = "101" ' Código 5 na remessa ???
ced.CedenteCOD = "33333334892001304444"    ' 20 digitos (note que o final, é o numero da conta, sem os ultios 2 digitos)
ced.Convenio = "0000000000000000002222220" ' 25 digitos
ced.useSantander = True 'importante para gerar o código de barras correto (por questão de compatibilidade o padrão é false)

Resolvi colocando tipo de carteira 1, mas quais são os tipos aceitáveis e quando é utilizando cada um deles?

Apresenta o ero
![2016-03-22_225638](https://cloud.githubusercontent.com/assets/17903664/13973423/616de42a-f081-11e5-928e-bea593319116.png)

Resolvi

**Comment by impactro** [comment]
Falta apenas especificar o Tipo da Carteira, é um campo que só é usado para remessa no Santrander

ced.CarteiraTipo = "5"

Sempre que quiser saber todos os parâmetros veja um dos exemplos comentados aqui:
https://github.com/impactro/Boleto-Test/blob/master/Santander.cs#L24
- 1 = ELETRÔNICA COM REGISTRO
- 3 = CAUCIONADA ELETRÔNICA
- 4 = COBRANÇA SEM REGISTRO
- 5 = RÁPIDA COM REGISTRO (BLOQUETE EMITIDO PELO CLIENTE)
- 6 = CAUCIONADA RAPIDA
- 7 = DESCONTADA ELETRÔNICA
