### ISSUE TITLE
Erro da DLL no vb6

### ISSUE THREAD

**Issue by jbsr** [impactro/Boleto-Test#8]
Fábio

Tive que formatar minha máquina e comecei do zero. Estou utilizando o VS 2012.

O que ocorre.

Eu estou compilando a dll original, sem fazer alteração alguma na estrutura da mesma.

A unica coisa que fiz, foi habilitar 'Register for COM interop' que cria os .tlb automaticamente.

Dentro do VB6, ocorrem os erros da seguinte forma.

Se eu crio a variável da seguinte forma:

dim ced as new CedenteInfo, gera o erro do arquivo 2016-03-24_121948

![2016-03-24_121948](https://cloud.githubusercontent.com/assets/17903664/14021737/9306a914-f1bb-11e5-8d59-ce9cd21e8a1a.png)

Se eu crio a variável da seguinte forma

dim ced as CedenteInfo, gera o erro do arquivo 2016-03-24_122009

![2016-03-24_122009](https://cloud.githubusercontent.com/assets/17903664/14021746/9ccc2d8e-f1bb-11e5-94ed-1cca2f46bc78.png)

Se eu declaro dessa forma:

Dim ced As New Impactro_Cobranca.CedenteInfo
Set ced = New Impactro_Cobranca.CedenteInfo

da esse erro:

![2016-03-24_121948](https://cloud.githubusercontent.com/assets/17903664/14021737/9306a914-f1bb-11e5-8d59-ce9cd21e8a1a.png)

Isso vale para todas as variáveis da dll.

O que pode estar ocorrendo? Pode me dar uma luz?

No aguardo.

Att

**Comment by impactro** [comment]
Antes de mais nada, você leu com atenção e segui os passos indicados no arquivo?

https://github.com/impactro/Boleto-VB6/blob/master/DLL/%23INSTRU%C3%87%C3%95ES-VB6.txt

Estes problemas com o VB6 estão sempre relacionados ao registro da DLL.
Faça sempre os procedimentos com o VB6 fechado.
E os diretórios onde você fizer o registro da DLL ficarão amarrados permanebtemente, a menos que você use o procedimento do GAC opcional.

Sempre desregistre tudo se ocorrer problemas, principalmente quando se muda a versão da DLL, por isso que eu coloco na descrição do componente o numero da versão, sendo assim necessário sempre primeiro remover a referencia, salvar o projeto, mesmo com erro, e reiniciar o VB6, e depois vincular a referencia corretamente.
