### ISSUE TITLE
Dúvida sobre o sicoob

### ISSUE THREAD

**Issue by diogolovizon** [impactro/Boleto-Test#9]
Olá Fábio,

Solicitaram a alteração neste item do boleto "4342/0000630" para "4342/**00**/0000630"
No manual eu não encontrei nada a respeito desse tipo de informação.

Exemplo: http://prntscr.com/ame0o6 e http://prntscr.com/ame0wh

Esta solicitação veio do pessoal do banco.

Existe alguma configuração ou motivo para ser desta maneira?
OBS: este boleto é do tipo **sem registro**

**Comment by impactro** [comment]
Melhorei isso, e logo estou subindo uma versão com esse ajuste
